/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DaoException;
import dao.*;
import domain.Party;
import domain.Policy;
import domain.Tag;
import gui.helpers.SimpleListModel;
import gui.helpers.ValidationHelper;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author soupa868
 */
public class DataEntry extends javax.swing.JDialog {

    private final PolicyDaoInterface dao;
    private final PartyDaoInterface partyDao;
    private final TagsDaoInterface tagsDao;
    private SimpleListModel categoryHolder = new SimpleListModel();
    private Policy policy = new Policy();
    private ValidationHelper validation = new ValidationHelper();

    /**
     * Creates new form DataEntry
     */
    public DataEntry(java.awt.Window parent, boolean modal, PolicyDaoInterface dao, PartyDaoInterface partyDao, TagsDaoInterface tagsDao) {
        super(parent);
        super.setModal(modal);

        initComponents();
        this.dao = dao;
        this.partyDao = partyDao;
        this.tagsDao = tagsDao;
//        tagText.setEditable(true);
        categoryHolder.updateItems(tagsDao.getTags());
//        txtCategory.setModel(categoryHolder);
        validation.addTypeFormatter(policyId, "#0", Integer.class);

        policyId.setName("txtID");
        policyDetails.setName("txtDescription");
        policyName.setName("txtName");
        tagsText.setName("txtCategory");
        partyName.setName("txtQuantity");
        saveButton.setName("saveButton");
        CancelButton.setName("CancelButton");
    }

    public DataEntry(java.awt.Window parent, boolean modal, Policy policy, PolicyDaoInterface dao, PartyDaoInterface partyDao, TagsDaoInterface tagsDao ) {
        // delegate initialisation to other constructor
        this(parent, modal, dao, partyDao, tagsDao);
        this.policy = policy;
        policyDetails.setText(policy.getText());
        policyId.setValue(policy.getId());
        policyName.setText(policy.getName());
        tagsText.setText(policy.getTags().toString());
        partyName.setText((policy.getParty().getName()));
        policyId.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        policyName = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        policyId = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        policyDetails = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tagsText = new javax.swing.JTextArea();
        partyName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Policy ID");

        jLabel2.setText("Name:");

        jLabel3.setText("policyDetails");

        jLabel4.setText("Tags");

        jLabel6.setText("party");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Product Editor");

        policyDetails.setColumns(20);
        policyDetails.setRows(5);
        jScrollPane2.setViewportView(policyDetails);

        tagsText.setColumns(20);
        tagsText.setRows(5);
        jScrollPane1.setViewportView(tagsText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 313, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(policyName)
                            .addComponent(policyId)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(partyName))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55)
                .addComponent(CancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(policyId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(policyName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(partyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(CancelButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            Integer id = (Integer) policyId.getValue();
            String name = policyName.getText();
            String policyText = policyDetails.getText();
            String[] tagTemp = tagsText.getText().split(" ");
            Collection<Tag> tags = new ArrayList<Tag>();
            for(String tag : tagTemp){
                tags.add(new Tag(tag));
            }
            tagsDao.addTags(tags);
            Party party = partyDao.getParty(partyName.getText());
            Date date = new Date();
            Policy policy = new Policy(id, name, policyText, party, tags, date);
            System.out.println(policy.toString());
//            if (id != null && policyId.isEditable()) {
//                if (dao.inDatabase(id)) {
//                    JOptionPane.showMessageDialog(this, "Item is in the database already");
//                    return;
//                }
//            }
            if (validation.isObjectValid(policy)) {

                dao.addPolicy(policy);
                
                categoryHolder.updateItems(tagsDao.getTags());
//        tagsText.setModel(categoryHolder); #todo check how the tags are stored for viewing in viewer.
                dispose();
            }
        } catch (DaoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "error in data", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_saveButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField partyName;
    private javax.swing.JTextArea policyDetails;
    private javax.swing.JFormattedTextField policyId;
    private javax.swing.JTextField policyName;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextArea tagsText;
    // End of variables declaration//GEN-END:variables
}
