/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

//import dao.DAO;
import dao.PartyDaoInterface;
import dao.PolicyDaoInterface;
import dao.TagsDaoInterface;

/**
 *
 * @author paulo
 */
public class MainMenu extends javax.swing.JFrame {

    private final PolicyDaoInterface dao;
    private final PartyDaoInterface partyDao;
    private final TagsDaoInterface tagsDao;

    /**
     * Creates new form MainMenu
     */
    public MainMenu(PolicyDaoInterface dao, PartyDaoInterface partyDao, TagsDaoInterface tagsDao) {
        this.dao = dao;
        this.partyDao = partyDao;
        this.tagsDao = tagsDao;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        newButton = new javax.swing.JButton();
        ViewBotton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        AddParty = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Main Menu");

        newButton.setText("Add new Product");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        ViewBotton.setText("View Product");
        ViewBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBottonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        AddParty.setText("Add a new Party");
        AddParty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPartyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addComponent(AddParty, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewBotton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddParty)
                .addGap(18, 18, 18)
                .addComponent(ExitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        DataEntry newProduct = new DataEntry(this, true, dao, partyDao, tagsDao);
        newProduct.setLocationRelativeTo(this);
        newProduct.setVisible(true);

    }//GEN-LAST:event_newButtonActionPerformed

    private void ViewBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBottonActionPerformed
        ViewProduct view = new ViewProduct(this, true, dao, partyDao, tagsDao);
        view.setLocationRelativeTo(this);
        view.setVisible(true);

    }//GEN-LAST:event_ViewBottonActionPerformed


    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void AddPartyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPartyActionPerformed
        test newParty = new test(this, true, partyDao);
        newParty.setLocationRelativeTo(this);
        newParty.setVisible(true);
    }//GEN-LAST:event_AddPartyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddParty;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton ViewBotton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton newButton;
    // End of variables declaration//GEN-END:variables
}
