@startuml

' style tweaks to make the diagram a little more readable
skinparam {
	Style strictuml
	RoundCorner 8

	Sequence {
		' make activations yellow too
		LifeLineBackgroundColor #FDFDCD

		' make stereotypes less ugly
		Stereotype {
			Font {
				Size 11
				Style plain
			}
		}
	}

	DatabaseBorderColor #A80036

}

title Add New Product (using DB DAO)

actor User as user
participant "Administration" as main << main >>
participant "MainMenu" as menu << frame >>
participant "ProductEditor" as dialog << dialog >>
participant "ProductDatabaseDAO" as dao << DAO >>
participant "SimpleListModel\n:model" as model
participant "Product\n:product" as product << domain >>
database "Database" as db

main++
create menu
main -> menu : « construct »

user -> menu : clicks 'Add New Product'
menu++

create dialog
menu -> dialog : « construct »
dialog++

create dao
dialog -> dao : « construct »

dialog -> dao++ : getCategories()
dao -> db++ : select distinct category from product
return ResultSet
dao -> dao : extract categories\nfrom ResultSet
return categories

create model
dialog -> model : « construct »

dialog -> model++ : updateItems(categories)
model--
dialog -> dialog : cmbCategory.setModel(model)
note left : categories now\nin combobox
dialog--



user -> dialog++ : enters product details into input components
dialog--

user -> dialog++ : clicks 'Save' button

create product
dialog -> product : « construct »

dialog -> dialog : get details entered\ninto input components

dialog -> product++ : set fields to entered details
product--

dialog -> dao++ : save(product)
dao -> dao : copy product details\ninto PreparedStatement
dao -> db++ : merge into product (...) values (...)
db--
dao--

dialog -> dialog : dispose()
dialog --> menu : menu regains focus
destroy dialog


@enduml
